### ISSUE TITLE
Always returning "fail"

### ISSUE THREAD

**Issue by cshunsinger** [wsguest/geetest#2]
So firstly let me mention that I could never have even begun to crack GeeTest without your code. However I had to take a slightly different approach.

The website that I am trying to pass GeeTest on will not load in Internet Explorer, nor will HttpWebRequests work. Idk why, I even tried changing the user agent but nothing worked. Instead I use CefSharp, a Chromium browser Winform element, to log in to the site that I am using.

So in short:
CefBrowser -> LoadPageWithGeeTest -> Parse GT and Challenge
var gk = new Geek(gt, challenge);

I modified your constructor to skip the GetConfig() part since GetConfig only loads a string that says "Old Challenge" since my winform browser already loaded that geetest.

```
public Geek(string gt, string challenge)
{
            config = new JsonObject();
            config["gt"] = gt;
            config["initchallenge"] = challenge;
            this.challenge = challenge;
            this.gt = gt;
            Console.WriteLine("Refresh Config: " + RefreshConfig());
}
```

All of the code works with no exceptions, but the final response I get is "fail". For all 4 actions that get executed:

```
result: {"success": 0,"message":"fail"}
result: {"success": 0,"message":"fail"}
result: {"success": 0,"message":"fail"}
result: {"success": 0,"message":"fail"}
```

Idk if this is an issue on my end or an issue with my code.

**Comment by caohai01** [comment]
I considered the most common scene of geetest,  if your aimed page was set "fullpage" to true, you should make a request to simulate mouse moving on page, otherwise,  "fail" may be returned. addtional types may be studied in the future. you can also draw a line or rectangle on the background image to confirm the "xpos".
good luck.

**Comment by wsguest** [comment]
I considered the most common scene of geetest only, and addtional types may be studied in the future. _If your aimed page was set "fullpage" to true, you should make a request to simulate mouse moving on page, otherwise, "fail" may be returned_(not necessary). you can also draw a line or rectangle on the background image to confirm whether the "xpos" is correct.
good luck.

**Comment by cshunsinger** [comment]
Well one thing I did notice is that the images returned from making a web request to refresh.php is that the image that came back had the puzzle shape shadow in a different x coordinate from the one shown on the web page.

I actually just found a way to obtain the pictures from the current web page, meaning there will be almost no need for me send a refresh.php request. I also discovered that there is a click.php?challenge-"" which has a different challenge string from the challenge string sent to get.php. In other words, I think I can bypass your GetConfig and RefreshConfig functions and utilize the others. I will let you know how it goes.

And thank you so much for posting your code. I have learned so much from it! Is there any chance you could tell me where you learned how to do some of this stuff? Like how did you know how to properly encrypt xpos, etc?

EDIT: Still getting fail message. I didn't have it draw a square around the puzzle piece. Instead I just opened Paint.NET and used a selection box to measure how many pixels. The algorithm always ends up being a few pixels off, but not by much. Could it maybe be GetResponseString? What encoding is used? I don't recognize the algorithm. Example output:

```
try pos: xpos (GetResponseString value)
try pos: 118 (88ff3333332b96)
result: {"success": 0,"message":"fail"}
```

EDIT2: It works!!!! I got it working!!! I am receiving a successful response. Now the only question is how to make the webpage recognize that. The Geetest box itself doesn't show as being completed which makes sense, but I expected pressing the "reward" button on that page would still recognize the successful GeeTest, but that is not an issue with this code.

**Comment by wsguest** [comment]
It will be highly appreciated if you are willing to post your discovery of obtaining pictures.
 PS: you'd better add the removed wait code in my last commit to achieve higher accuracy.

**Comment by cshunsinger** [comment]
I have the latest version of your code. I will post my discovery. Do you want me to post here or elsewhere? The only question is where do I stick the validation code in order to make the captcha element itself recognize that it's been solved, or to make the solebtc page itself think it's been solved (since it technically has been solved). That last thing to figure out (famous last words).

**Comment by cshunsinger** [comment]
Also what does the wait code provide higher accuracy?

**Comment by wsguest** [comment]
Post your discovred url here or open a new issue, according to your wishes. To make the page think you had passed, post your data (username, password etc) with the validation to server, just like you press the login/submit button on page. The removed wait code makes it simulate human actions more realistic.

**Comment by cshunsinger** [comment]
Ok, so first let me address your question about how to get the images. The geetest URLs, at least for http://solebtc.com, are in the header, not the body. That doesn't matter because IndexOf doesn't give a shit. First look for:
`<div class="gt_cut_bg gt_show">`
Underneath that will be something like:
`<div class="gt_cut_bg_slice" style="background-image: url("https://static.geetest.com/pictures/gt/b6c769602/bg/5f60c2928.webp"); background-position: -157px -58px;"></div>`

The url to the scrambled image is the same url as above, but replace .webp with .jpg. Now there will be many repeats of the above but with different background positions. If you didn't know their scrambling algorithm (but you do) then all of these combined could be used to make the full image, but we don't care because we know how to descramble-- oh yeah we need the ypos...

After getting the info for your bg image, under all the `<div class="gt_cut_bg_slice">` divs you will eventually see the following/similar div:
`<div class="gt_slice gt_show" style="left: 0px; width: 56px; height: 52px; top: 48px; background-image: url(&quot;https://static.geetest.com/pictures/gt/b6c769602/slice/5f60c2928.png&quot;);"></div>'''
`height:``` is going to be your ypos.

The stuff to look for with the fullbg image is:
`<div class="gt_cut_fullbg gt_show">`
Underneath that will be something like:
`<div class="gt_cut_fullbg_slice" style="background-image: url("https://static.geetest.com/pictures/gt/b6c769602/bg/5f60c2928.webp"); background-position: -157px -58px;"></div>`

There is now still a small problem. The challenge string found in the get.php? call is wrong and will not work with your function for encoding the xpos into something that will be accepted by the geetest server. We need the right challenge hash. So just look for a url like: `https://api.geetest.com/click.php?challenge=0959ac5d9adc9d9630422a95e6aad79bgt` and parse the challenge hash from there. That challenge hash will be different from the challenge hash in `https://api.geetest.com/get.php?gt=5c17ac67511f4174d0861e0ae16e5975&challenge=0959ac5d9adc9d9630422a95e6aad79b`

At this point you now have ypos, bg url, fullbg url, and the REAL challenge hash string. So I just modify your code in GetValidate to use those values and your code does the rest. Basically I parsed the raw html to do the job of your GetConfig and RefreshConfig functions.

Now getting back to my problem. I am not certain how to go about that. The website I am trying to bot is heavily javascripted. I am attempting to figure this one out myself, but basically it's a tad difficult on this site to find what is being called when the button is clicked. But like I said, I might be able to figure it out myself.

What I do know is that there is a callback in the geetest urls. I assume when you manually complete the geetest this callback name is used somehow. I mean, when you receive the json object after submitting the geetest xpos, the json object is named after the callback name. I think I just need to send the json object with the success and validation values to the geetest, but I can't quite figure out how to do that.

**Comment by wsguest** [comment]
thanks, it's very useful. 
If you worked with a browser, or a browser kernel, a javascript version may be more suitable. you can catch the interactive process by develope tool, for example F12 in Chrome,  and will see how thoes validations are submitted. Simulating that process by javascript snippet will solve your problem.

**Comment by cshunsinger** [comment]
Well I am new to the web scene. Very new to it. I have tried using chrome dev tools to record all of the script calls when I manually fill out a geetest captcha, but I haven't had any luck tracing it. Plus as an added bonus the javascript for geetest is obfuscated :/

**Comment by wsguest** [comment]
I want to help you, but when I opened http://solebtc.com,  no geetest captacha was found.

**Comment by cshunsinger** [comment]
Well you have to register. You're under no obligation to do so but if you wanted to check it outbfor the hell of it then you could register with a fake email and a bitcoin address. It doesn't matter what bitcoin address unless you actually want to earn bitcoins. If you help me with this then I will most certainly send you the completed software that I will use to bot them. It is nice because you can not with many accounts at once.

**Comment by cshunsinger** [comment]
Bot with many accounts*

**Comment by wsguest** [comment]
I followed your instructions to register a account, everything seems goes well until I tried to get a new challenge using click.php, it returned nothing with status code 302, which means such URL is temporarily moved.

**Comment by wsguest** [comment]
I got the point of click.php, but using refresh.php. To get the bonus, you can request the url https://solebtc.com/api/v1/incomes/rewards with custom header: 
`X-Geetest-Challenge:485d049883499cadfca759e5063402e7kr
X-Geetest-Seccode:0479995d0edbe2ab4dc2a7f8a2f66feb|jordan
X-Geetest-Validate:0479995d0edbe2ab4dc2a7f8a2f66feb
Auth-Token:c8850ecb-xxxx-xxxx-xxxx-043f12544db6
Cookie: crisp-client%2Fsession%2Fstr-str-str..`

**Comment by cshunsinger** [comment]
Ok so I just send a HttpWebRequest to https://solebtc.com/api/v1/incomes/rewards with those headers, filling in for the challenge code, validation code, etc.

I never did notice that the Seccode is just the validation code with "|jordan" at the end of it, or is this a coincidence?
And then the Cookie header is just the name of the cookie holding the session key while the value of that session cookie contains the auth-token?
And, presumably, by calling that URL with those headers, the website will believe that the Geetest was completed. I would appreciate confirmation on the above so I know for sure that I know where to get the different keys.

Thank you so much for you help! I guess we were able to help each other. For learning purposes I am curious to know how you found this out. In the future I hope to be able to fend for myself or to help others with this kind of stuff. I spent the last few days looking at the crisp and geetest javascript. Even found a deobfuscator that did a decent job. I found that `window` has a `Geetest` object who's prototype had some public functions, but there wasn't really anything useful in that. I couldn't find anything in the Crisp client code either.

**Comment by cshunsinger** [comment]
Odd. When I make a web request to that url I just get a 401 error.

Ahh now I see. I was sending everything right, but the Auth-Token header. I was sending it, but it wasn't correct. This is most likely why I was getting the 401. However, I am unsure from where to obtain or parse this token. It doesn't seem to come from any get request. It's like the client side just manages to conceive it out of thin air, which means it is likely being generated by the javascript code.

**Comment by wsguest** [comment]
401 means you are making a unauthorized request. 
The Auth-Token or Auth-Cookie are not groundless, generally, they are assigned values after you login successfully.

**Comment by cshunsinger** [comment]
Well the Auth-Token isn't stored as a cookie in this case. Just the session token. So other than the Auth-Token, I have managed to code things to send all of the right headers with the right values. So hopefully once I fetch the Auth-Token for the account being botted then that will fix the problem.

**Comment by cshunsinger** [comment]
Well, I tried using HttpWebRequest to get the Auth-Token since I found out that goes through https://solebtc.com/api/v1/auth_token. Gave me 401. So I tried using the CefSharp browser since I couldn't get HttpWebRequest working. I just simply couldn't find a way to get the auth token returned by the server when the browser naturally logged in.

Then I had an idea. By merely loading the reward page, before I had to do anything with the Geetest, the CefSharp browser has to send a custom header containing the auth token to the server in order to load the reward page. So using that I was able to pull the auth token.

Then I tried using HttpWebRequest again in order to actually claim the reward from "solving" the Geetest. But it had yet another exception, but to my surprise, when I reloaded the software (after making some minor tweaks) and the browser loaded to the reward page, instead of the green reward button, I got the countdown timer! Even though the request threw an exception, the post worked and I successfully ran my first fully automated reward claim!!!

Holy shit dude thank you so fucking much for your help! I gotta clean this code up a tad, but if you want a copy of the sourcecode then just tell me. Idk if you might have any use for the code.

**Comment by wsguest** [comment]
Excellent job! Congratulations!
The solved Geetest hashes will remain valid in a few minutes, about 10-15,  you can compute them in batches and then store them for immediately using.
I will close this issue, if you allowed.

**Comment by cshunsinger** [comment]
Cool. Yeah we can close the issue, and once again thanks for your help!

**Comment by hieplpvip** [comment]
Could you send me a copy of your source code please? Thank you sir!
Here is my email: baohiep2013@gmail.com
@TF2274
