### ISSUE TITLE
Geetest Always Failing - And With Private Proxies

### ISSUE THREAD

**Issue by cshunsinger** [wsguest/geetest#4]
As the title says, I think this is something to be revisited.

How did you figure out the algorithms for how to encode everything such as the actions, timing, etc? I think something had to have been changed. I gave my bot a rest for multiple days but it can't solve a single captcha anymore. However I can solve them manually with no problem. I'm really starting to suspect that maybe there has been an update to their algorithm.

**Comment by wsguest** [comment]
Does the demo url work in your browsers? The algorithms come from javascript code loaded by the browser.

**Comment by cshunsinger** [comment]
The demo mostly works, but this is the Geetest website demo (http://geetest/com). I don't know of any other website that has a Geetest that doesn't require a login. Plus the gt string changes with each test on any other website (which I have coded for myself since your code has worked for a while).

It's just that I used to run 60 accounts from one IP address. Now I have 120 accounts and 20 proxies, so only 6 accounts bound to one IP address. So the Geetest API wasn't seeing many test attempts at all from each IP address.

They have their Geetest javascript code highly obfuscated. I'm getting better at Javascript, but I'm not at the level of proficiently reading obfuscated Javascript. I just feel like something may have changed in their algorithm or something. I don't know why your code would be failing me even after many days of giving it a break so my proxy IPs could maybe drop off of their flag list.

These are private proxies btw, that I paid a monthly fee for. Not just public proxies that basically don't work at all.

**Comment by wsguest** [comment]
I tested my demo project, it worked as expected. I used the second constructor to make a instance of Geek class.
`var gk = new Geek(new Uri("http://solebtc.com/api/v1/captchas"));`
and changed the constructor code to
`8. this.gt = obj.Get<string>("captcha_id"); // from obj.Get<string>("gt");`
according to the returned json from the captcha url.
good luck!

**Comment by hieplpvip** [comment]
I'm having the same problem. Can't get any validate, always failed.
