### ISSUE TITLE
Always return forbidden

### ISSUE THREAD

**Issue by hieplpvip** [wsguest/geetest#6]
Hello. I got 'forbidden' everytime I tried to get validate. Could some one help me? @wsguest 
Thanks very much

**Comment by yqMac** [comment]
Change the course of generating rules.

发自我的 iPhone

**Comment by wsguest** [comment]
the generate/generate2 function was targeted ,  read and change it.

**Comment by hieplpvip** [comment]
Could you tell more clearly?
